[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/PacktPublishing/Data-Strategy-for-LLMs/blob/main/chapter_05/Jupyter_Notebooks/Chapter_5_Notebook.ipynb)

**Click the badge above to run this notebook in Google Colab (no local setup needed).**


# Chapter 5: Data Strategy for Advanced RAG

This notebook builds on Chapters 3 and 4. We reuse the same ChromaDB database and `ask_rag()` function,
then demonstrate the **five data problems** that break Naive RAG in production, and how to fix each one.

**Prerequisites:** Run Chapter 4 notebook first (creates the shared ChromaDB collection).

## Setup: Reuse Chapter 4 Environment

In [1]:
import warnings; warnings.filterwarnings("ignore")
import sys, os, subprocess
from pathlib import Path

# Find repo root (walk up until we find utils/)
cwd = Path.cwd()
repo_root = cwd
for p in [cwd] + list(cwd.parents):
    if (p / 'utils').is_dir():
        repo_root = p
        break

# Install minimal deps quietly
for pkg in ['chromadb', 'openai', 'python-dotenv', 'numpy']:
    subprocess.run([sys.executable, '-m', 'pip', 'install', pkg, '-q'],
                   capture_output=True)

# Load API key - try multiple locations so it works from any working directory
from dotenv import load_dotenv
env_paths = [
    repo_root / '.env',                    # repo root (normal run)
    Path.home() / 'code/personal/books/Data-Strategy-for-LLMs/.env',  # absolute fallback
    Path('.env'),                           # current directory
]
for env_path in env_paths:
    if env_path.exists():
        load_dotenv(env_path)
        print('Loaded .env')
        break

pass  # repo-root print removed (avoids leaking local path)
print(f'OpenAI key loaded: {"yes" if os.getenv("OPENAI_API_KEY") else "NO - create .env with OPENAI_API_KEY=sk-..."}')


OpenAI key loaded: yes


In [2]:
# Connect to the SAME ChromaDB from Chapter 4
import chromadb

SHARED_DB = repo_root / 'data' / 'chroma_db'
client = chromadb.PersistentClient(path=str(SHARED_DB))

# Open Chapter 4's collection
book_collection = client.get_or_create_collection(name='book_collection')
print(f'Collection: {book_collection.name}')
print(f'Documents from Ch4: {book_collection.count()}')

# Show what Ch4 indexed
existing = book_collection.get()
for i, doc in enumerate(existing['documents']):
    print(f'  [{existing["ids"][i]}] {doc[:80]}...')


Collection: book_collection
Documents from Ch4: 0


In [3]:
# Reuse ask_ai() from Chapter 4, with self-updating model discovery
from openai import OpenAI

ai_client = OpenAI()

# Discover the best available model (self-updating, cached between runs)
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))
from utils.models import get_best_available_model, patch_client_compat
patch_client_compat(ai_client)   # tolerate newer-model parameter rules (temperature, max_tokens)
MODEL = get_best_available_model(ai_client)

def ask_ai(content: str) -> str:
    """Send a prompt to the LLM and return the response."""
    response = ai_client.chat.completions.create(
        model=MODEL,
        messages=[{'role': 'user', 'content': content}],
        temperature=0
    )
    return response.choices[0].message.content

# Quick test
print(ask_ai('Say hello in exactly 3 words.'))

Selected model: gpt-5.5  (live, 69 candidates)


Hello, dear friend.


In [4]:
# Reuse ask_rag() from Chapter 4 (baseline Naive RAG)
def ask_rag(query: str, collection=None, n_results=2, debug=True):
    """Chapter 4 baseline: vector search + LLM generation."""
    if collection is None:
        collection = book_collection
    results = collection.query(
        query_texts=[query], n_results=n_results,
        include=['documents', 'distances', 'metadatas']
    )
    docs = results['documents'][0]
    distances = results['distances'][0]
    metadatas = results['metadatas'][0]
    context = '\n---\n'.join(docs)

    if debug:
        print(f'Query: {query}')
        for i, doc in enumerate(docs):
            meta = metadatas[i] if metadatas else {}
            print(f'  Result {i+1} (distance: {distances[i]:.4f}): {doc[:80]}...')
            if meta:
                print(f'    Metadata: {meta}')
        print()

    prompt = f"""You are an expert assistant. Use ONLY the following context to answer.
If the answer is not in the context, say so. Do not make up information.

<context>{context}</context>
<question>{query}</question>
Answer:"""
    return ask_ai(prompt)

# Test with Ch4 data
print(ask_rag('What is the new AI policy?'))


Query: What is the new AI policy?



The context does not provide any information about a new AI policy.


---
## Create Chapter 5 Collection with Rich Data

The 4 documents from Chapter 4 are too simple to show real RAG failures.
We create a new collection with **25 documents** that have:
- Ticket IDs and identifiers
- Multiple versions of the same document
- Documents from different tenants/departments
- Formal and informal vocabulary
- Cross-referencing information across documents

In [5]:
from datetime import datetime

# Create a fresh collection for Chapter 5 demos
try:
    client.delete_collection('ch5_advanced_rag')
except:
    pass
ch5 = client.create_collection(name='ch5_advanced_rag',
                               metadata={'hnsw:space': 'cosine'})

# === DOCUMENTS WITH RICH METADATA ===
documents = [
    # --- Identifier documents (for Issue 1: Mixed Content Types) ---
    {'id': 'TICKET-1234', 'text': 'TICKET-1234: OAuth login times out after 30 seconds on mobile. '
     'Steps to reproduce: open app, tap login, wait. Assigned to Sarah Chen. Priority: P1.',
     'meta': {'type': 'ticket', 'status': 'open', 'project': 'AUTH',
              'created': '2024-11-01', 'tenant': 'internal'}},

    {'id': 'TICKET-1235', 'text': 'TICKET-1235: Dashboard charts fail to render on Safari 17. '
     'Charts show blank white space. Console shows WebGL error. Assigned to Mike Park.',
     'meta': {'type': 'ticket', 'status': 'closed', 'project': 'UI',
              'created': '2024-10-15', 'tenant': 'internal'}},

    {'id': 'TICKET-5678', 'text': 'TICKET-5678: API rate limiter returns 429 for authenticated users. '
     'Throttle threshold set to 100/min but triggers at 50/min. Linked PR: PR-441.',
     'meta': {'type': 'ticket', 'status': 'in_progress', 'project': 'API',
              'created': '2024-12-01', 'tenant': 'internal'}},

    # --- Versioned documents (for Issue 2: Temporal Drift) ---
    {'id': 'coding_std_v2', 'text': 'Code Conventions v2: All Java classes must use camelCase for methods, '
     'PascalCase for classes. Use Javadoc for all public methods. Maximum method length: 50 lines. '
     'Mandatory code review by two senior developers. Unit test coverage minimum: 80%. '
     'Follow the factory pattern for object creation. Use dependency injection throughout.',
     'meta': {'type': 'policy', 'version': 2, 'superseded': True,
              'last_updated': '2021-03-15', 'tenant': 'internal'}},

    {'id': 'coding_std_v3', 'text': 'Code Conventions v3 (CURRENT): Use Python type hints on all functions. '
     'Follow PEP 8. Maximum function length: 30 lines. Prefer composition over inheritance.',
     'meta': {'type': 'policy', 'version': 3, 'superseded': False,
              'last_updated': '2024-09-10', 'tenant': 'internal'}},

    {'id': 'install_guide_v2.1', 'text': 'Installation Guide v2.1: Download the installer from the releases page. '
     'Run setup.exe with administrator privileges. Configure the database connection string '
     'in config.xml. Set the OAuth timeout to 900 seconds. Restart all services after installation. '
     'Verify by accessing the health endpoint at /api/health.',
     'meta': {'type': 'guide', 'version': 2.1, 'superseded': True,
              'last_updated': '2023-08-15', 'tenant': 'internal'}},

    {'id': 'install_guide_v2.5', 'text': 'Installation Guide v2.5 (CURRENT): Use the CLI installer. '
     'Run: ./install --auto. OAuth timeout is now 300 seconds (changed from 900).',
     'meta': {'type': 'guide', 'version': 2.5, 'superseded': False,
              'last_updated': '2024-11-20', 'tenant': 'internal'}},

    # --- Multi-tenant documents (for Issue 3: ACL Leakage) ---
    {'id': 'case_acme_001', 'text': 'Acme Corp: Q4 cash reconciliation shows $2.3M discrepancy '
     'in the fixed income portfolio. Root cause: missing coupon payments from 3 bonds.',
     'meta': {'type': 'case', 'tenant': 'acme_corp', 'account_id': 'ACC-001',
              'created': '2024-12-01'}},

    {'id': 'case_acme_002', 'text': 'Acme Corp: Monthly recon log for November shows all positions matched. '
     'No breaks found. Total AUM: $450M.',
     'meta': {'type': 'case', 'tenant': 'acme_corp', 'account_id': 'ACC-001',
              'created': '2024-12-05'}},

    {'id': 'case_globex_001', 'text': 'Globex Inc: Cash balance mismatch of $890K in the equity portfolio. '
     'Custodian reports different settlement date. Escalated to operations team.',
     'meta': {'type': 'case', 'tenant': 'globex_inc', 'account_id': 'ACC-002',
              'created': '2024-11-28'}},

    {'id': 'case_globex_002', 'text': 'Globex Inc: Annual compliance review completed. '
     'All regulatory filings submitted on time. Total AUM: $1.2B.',
     'meta': {'type': 'case', 'tenant': 'globex_inc', 'account_id': 'ACC-002',
              'created': '2024-12-10'}},

    {'id': 'case_wayne_001', 'text': 'Wayne Enterprises: Portfolio rebalancing request for Q1. '
     'Shift 15% from fixed income to equities. Total AUM: $3.8B.',
     'meta': {'type': 'case', 'tenant': 'wayne_ent', 'account_id': 'ACC-003',
              'created': '2024-12-12'}},

    # --- Informal/formal vocabulary (for Issue 4: Vocabulary Mismatch) ---
    {'id': 'doc_auth_formal', 'text': 'Authentication Failure Troubleshooting: When users experience '
     'authentication failures, verify the OAuth2 token expiration, check the identity provider '
     'status, and review the SAML assertion response codes.',
     'meta': {'type': 'runbook', 'tenant': 'internal', 'created': '2024-06-01'}},

    {'id': 'doc_perf_formal', 'text': 'Performance Degradation Runbook: When response time exceeds '
     'the P99 threshold of 500ms, check the connection pool utilization, review the query '
     'execution plans, and verify the CDN cache hit ratio.',
     'meta': {'type': 'runbook', 'tenant': 'internal', 'created': '2024-06-01'}},

    {'id': 'doc_mfa_setup', 'text': 'Multi-Factor Authentication Setup: Configure MFA by navigating '
     'to Security Settings, selecting Authentication Methods, and enabling TOTP or hardware key.',
     'meta': {'type': 'guide', 'tenant': 'internal', 'created': '2024-07-15'}},

    # --- Cross-referencing documents (for Issue 5: Multi-Hop) ---
    {'id': 'jira_oauth_bug', 'text': 'TICKET-9001: OAuth timeout bug. Users on mobile cannot login. '
     'Root cause: token refresh logic has off-by-one error. Fix merged in PR-552.',
     'meta': {'type': 'ticket', 'project': 'AUTH', 'linked_pr': 'PR-552',
              'tenant': 'internal', 'created': '2024-10-01'}},

    {'id': 'pr_552', 'text': 'PR-552: Fix OAuth token refresh timing. Changed refresh window '
     'from 30s to 60s before expiry. Approved by Sarah Chen. Merged to main branch Oct 10.',
     'meta': {'type': 'pull_request', 'linked_ticket': 'TICKET-9001',
              'linked_release': 'v2.5.1', 'tenant': 'internal', 'created': '2024-10-10'}},

    {'id': 'release_v2.5.1', 'text': 'Release Notes v2.5.1: Deployed to production on October 15, 2024. '
     'Includes fix for OAuth timeout (PR-552). Also includes dashboard performance improvements.',
     'meta': {'type': 'release_notes', 'includes_pr': 'PR-552',
              'tenant': 'internal', 'created': '2024-10-15'}},

    # --- Error code runbooks (for Issue 1: Identifier Failure) ---
    {'id': 'runbook_401', 'text': 'Troubleshooting HTTP 401 Unauthorized: This error means the '
     'authentication token has expired or is invalid. Fix: check token expiration, '
     'refresh the OAuth token, verify the identity provider is responding.',
     'meta': {'type': 'runbook', 'error_code': '401', 'tenant': 'internal',
              'created': '2024-06-01'}},

    {'id': 'runbook_403', 'text': 'Troubleshooting HTTP 403 Forbidden: This error means the user '
     'is authenticated but does not have permission to access the resource. Fix: check '
     'the users role assignments, verify the ACL for the resource, review RBAC policy.',
     'meta': {'type': 'runbook', 'error_code': '403', 'tenant': 'internal',
              'created': '2024-06-01'}},

    {'id': 'runbook_500', 'text': 'Troubleshooting HTTP 500 Internal Server Error: This error means '
     'the server encountered an unexpected condition. Fix: check application logs for '
     'stack traces, verify database connectivity, review recent deployments.',
     'meta': {'type': 'runbook', 'error_code': '500', 'tenant': 'internal',
              'created': '2024-06-01'}},

    {'id': 'runbook_429', 'text': 'Troubleshooting HTTP 429 Too Many Requests: This error means '
     'the client exceeded the rate limit. Fix: implement exponential backoff, check '
     'the Retry-After header, review the API rate limit configuration.',
     'meta': {'type': 'runbook', 'error_code': '429', 'tenant': 'internal',
              'created': '2024-06-01'}},

    {'id': 'runbook_502', 'text': 'Troubleshooting HTTP 502 Bad Gateway: This error means the '
     'upstream server returned an invalid response. Fix: check if backend service is '
     'running, verify proxy configuration, review load balancer health checks.',
     'meta': {'type': 'runbook', 'error_code': '502', 'tenant': 'internal',
              'created': '2024-06-01'}},

    {'id': 'runbook_503', 'text': 'Troubleshooting HTTP 503 Service Unavailable: This error means '
     'the server is temporarily unable to handle requests. Fix: check CPU and memory '
     'utilization, verify auto-scaling is triggered, review circuit breaker settings.',
     'meta': {'type': 'runbook', 'error_code': '503', 'tenant': 'internal',
              'created': '2024-06-01'}},

    # --- HR/sensitive documents (for ACL demo) ---
    {'id': 'hr_salary_bands', 'text': 'HR CONFIDENTIAL: 2024 salary bands. Junior Engineer: $95K-$130K. '
     'Senior Engineer: $150K-$200K. Staff Engineer: $200K-$280K. Director: $250K-$350K.',
     'meta': {'type': 'hr_confidential', 'tenant': 'internal',
              'acl_role': 'hr_admin', 'created': '2024-01-15'}},

    {'id': 'hr_pto_policy', 'text': 'PTO Policy: Full-time employees accrue 20 days per year. '
     'Contractors do not accrue PTO. Carryover maximum: 5 days.',
     'meta': {'type': 'policy', 'tenant': 'internal',
              'acl_role': 'all_employees', 'created': '2024-02-01'}},
]

# Index all documents
ch5.add(
    ids=[d['id'] for d in documents],
    documents=[d['text'] for d in documents],
    metadatas=[d['meta'] for d in documents]
)
print(f'Indexed {ch5.count()} documents with rich metadata')


Indexed 26 documents with rich metadata


---
## Issue 1: Temporal Drift -- Old Documents Win

The old coding standards doc (v2) has more content than the new one (v3),
so it scores higher in similarity search. The system has no concept of time.


In [6]:
# PROBLEM: Old version outranks new version
print('=== Search: "coding standards" ===')
results = ch5.query(
    query_texts=['What are the coding standards?'], n_results=5,
    include=['documents', 'distances', 'metadatas']
)
for i, doc in enumerate(results['documents'][0]):
    dist = results['distances'][0][i]
    meta = results['metadatas'][0][i]
    version = meta.get('version', '-')
    superseded = meta.get('superseded', '-')
    updated = meta.get('last_updated', '-')
    print(f'  {i+1}. (dist: {dist:.4f}) v{version} | superseded={superseded} | updated={updated}')
    print(f'     {doc[:80]}...')
    print()

print('PROBLEM: The old, superseded version may rank higher because it has more content.')


=== Search: "coding standards" ===
  1. (dist: 0.6393) v2 | superseded=True | updated=2021-03-15
     Code Conventions v2: All Java classes must use camelCase for methods, PascalCase...

  2. (dist: 0.7100) v3 | superseded=False | updated=2024-09-10
     Code Conventions v3 (CURRENT): Use Python type hints on all functions. Follow PE...

  3. (dist: 0.8656) v- | superseded=- | updated=-
     Globex Inc: Annual compliance review completed. All regulatory filings submitted...

  4. (dist: 0.8996) v- | superseded=- | updated=-
     TICKET-5678: API rate limiter returns 429 for authenticated users. Throttle thre...

  5. (dist: 0.9048) v- | superseded=- | updated=-
     PTO Policy: Full-time employees accrue 20 days per year. Contractors do not accr...

PROBLEM: The old, superseded version may rank higher because it has more content.


In [7]:
# FIX: Filter out superseded documents BEFORE search
print('=== FIX: Search with supersession filter ===')
results = ch5.query(
    query_texts=['What are the coding standards?'], n_results=5,
    where={'superseded': False},  # <-- THIS IS THE FIX
    include=['documents', 'distances', 'metadatas']
)
for i, doc in enumerate(results['documents'][0]):
    dist = results['distances'][0][i]
    meta = results['metadatas'][0][i]
    version = meta.get('version', '-')
    updated = meta.get('last_updated', '-')
    print(f'  {i+1}. (dist: {dist:.4f}) v{version} | updated={updated}')
    print(f'     {doc[:80]}...')
    print()

print('FIX: Only current (non-superseded) documents appear.')


=== FIX: Search with supersession filter ===
  1. (dist: 0.7100) v3 | updated=2024-09-10
     Code Conventions v3 (CURRENT): Use Python type hints on all functions. Follow PE...

  2. (dist: 1.0389) v2.5 | updated=2024-11-20
     Installation Guide v2.5 (CURRENT): Use the CLI installer. Run: ./install --auto....

FIX: Only current (non-superseded) documents appear.


In [8]:
# FIX 2: Decay scoring for gradual staleness
# Decay is for documents that age continuously WITHOUT a clear successor
# (advisories, runbooks, troubleshooting notes). Versioned documents do not
# need it: the superseded filter from the previous fix already handles them.
from datetime import datetime, timedelta

# Self-contained demo: three troubleshooting notes about the same gateway
# timeout problem, written at different times. None of them replaces the
# others, so there is no superseded flag to filter on. Ages are relative to
# the day you run this cell, so the demo behaves the same on any date.
today = datetime.now()
notes = [
    {'id': 'note_500d', 'text': 'Gateway timeout troubleshooting: if the gateway '
     'returns a timeout, restart the proxy service and check the upstream health '
     'endpoint. Known issue with the legacy proxy image.',
     'meta': {'type': 'runbook',
              'last_updated': (today - timedelta(days=500)).strftime('%Y-%m-%d')}},
    {'id': 'note_200d', 'text': 'Gateway timeout incidents: most timeouts trace '
     'back to connection pool exhaustion. Check pool utilization before '
     'restarting anything.',
     'meta': {'type': 'runbook',
              'last_updated': (today - timedelta(days=200)).strftime('%Y-%m-%d')}},
    {'id': 'note_20d', 'text': 'Timeout errors at the edge: since the mesh '
     'migration, most edge timeout alerts are caused by stale DNS entries in '
     'the sidecar cache. Flush the sidecar DNS cache first.',
     'meta': {'type': 'runbook',
              'last_updated': (today - timedelta(days=20)).strftime('%Y-%m-%d')}},
]

try:
    client.delete_collection('ch5_decay_demo')
except:
    pass
decay_demo = client.create_collection(name='ch5_decay_demo',
                                      metadata={'hnsw:space': 'cosine'})
decay_demo.add(ids=[n['id'] for n in notes],
               documents=[n['text'] for n in notes],
               metadatas=[n['meta'] for n in notes])

HALF_LIFE_DAYS = {'policy': 180, 'guide': 90, 'runbook': 60, 'ticket': 30}
DEFAULT_AGE_DAYS = 365  # unknown age: assume stale, never reward a missing date

def decay_weight(last_updated_str, content_type):
    """Freshness weight in (0, 1]. Fresh docs keep ~1.0, old docs fade toward 0."""
    if not last_updated_str or last_updated_str == '-':
        age_days = DEFAULT_AGE_DAYS
    else:
        age_days = (datetime.now() - datetime.fromisoformat(last_updated_str)).days
    half_life = HALF_LIFE_DAYS.get(content_type, 90)
    return 0.5 ** (max(age_days, 0) / half_life)

def decayed_similarity(distance, last_updated_str, content_type):
    """Cosine distance -> similarity, weighted by freshness. Higher = better."""
    similarity = 1.0 - distance  # cosine space: distance = 1 - similarity
    return similarity * decay_weight(last_updated_str, content_type)

print('=== FIX 2: Decay scoring on troubleshooting notes (no successor documents) ===')
results = decay_demo.query(
    query_texts=['gateway returns a timeout, how do I troubleshoot it?'], n_results=3,
    include=['documents', 'distances', 'metadatas']
)
print('Before decay scoring (similarity only):')
for i, doc in enumerate(results['documents'][0]):
    dist = results['distances'][0][i]
    meta = results['metadatas'][0][i]
    print(f'  {i+1}. similarity={1.0-dist:.4f} | updated {meta["last_updated"]} | {doc[:60]}...')

print('\nAfter decay scoring (similarity x freshness):')
scored = []
for i, doc in enumerate(results['documents'][0]):
    dist = results['distances'][0][i]
    meta = results['metadatas'][0][i]
    adj = decayed_similarity(dist, meta.get('last_updated'), meta.get('type'))
    scored.append((adj, 1.0 - dist, meta, doc))
scored.sort(key=lambda x: x[0], reverse=True)  # higher = better
for rank, (adj, sim, meta, doc) in enumerate(scored, 1):
    print(f'  {rank}. score={adj:.4f} (similarity {sim:.4f}) | updated {meta["last_updated"]} | {doc[:60]}...')

print('\nBoth older notes outrank the current one on raw similarity because their')
print('wording matches the query. Decay scoring surfaces the current note instead.')


=== FIX 2: Decay scoring on troubleshooting notes (no successor documents) ===


Before decay scoring (similarity only):
  1. similarity=0.7369 | updated 2026-01-28 | Gateway timeout incidents: most timeouts trace back to conne...
  2. similarity=0.6501 | updated 2025-04-03 | Gateway timeout troubleshooting: if the gateway returns a ti...
  3. similarity=0.4288 | updated 2026-07-27 | Timeout errors at the edge: since the mesh migration, most e...

After decay scoring (similarity x freshness):
  1. score=0.3403 (similarity 0.4288) | updated 2026-07-27 | Timeout errors at the edge: since the mesh migration, most e...
  2. score=0.0731 (similarity 0.7369) | updated 2026-01-28 | Gateway timeout incidents: most timeouts trace back to conne...
  3. score=0.0020 (similarity 0.6501) | updated 2025-04-03 | Gateway timeout troubleshooting: if the gateway returns a ti...

Both older notes outrank the current one on raw similarity because their
wording matches the query. Decay scoring surfaces the current note instead.


**Book snippet -- Issue 1: Temporal Drift**
> The fix has two parts. First, store `last_updated`, `version`, and a `superseded` flag
> with every document at ingestion time. Second, at query time, filter out superseded
> documents and apply a decay score that reduces the ranking of older content.


---
## Issue 2: When Vector Search Sees the Pattern but Not the Value

Vector search captures **meaning**, not exact strings. When a support engineer
searches for "error 502", the embedding model sees "a server error" but cannot
read the specific code. It returns the 503 runbook instead, with a completely
different fix.


A support engineer sees "502 Bad Gateway" in their terminal and searches for it.
The wiki has separate runbooks for each HTTP error code. Vector search returns
the wrong one because all server errors look identical in embedding space.


In [9]:
# PROBLEM: Vector search cannot distinguish error codes
# A user sees "502 Bad Gateway" in their terminal and searches for it.
# The wiki has separate runbooks for 401, 403, 429, 500, 502, 503, 504.
# Vector search returns the WRONG runbook because all 5xx errors look similar.

print('=== Vector search for "server returns 502" ===')

# This simulates the support engineer searching for "server returns 502"
results = ch5.query(query_texts=['server returns 502'], n_results=4,
                     include=['documents', 'distances', 'metadatas'])
for i, doc in enumerate(results['documents'][0]):
    dist = results['distances'][0][i]
    meta = results['metadatas'][0][i]
    code = meta.get('error_code', '-')
    correct = 'CORRECT' if code == '502' else 'WRONG'
    print(f'  {i+1}. (dist: {dist:.4f}) [{correct}] error={code} | {doc[:70]}...')

print()
print('The 503 runbook (Service Unavailable) outranks the 502 runbook (Bad Gateway).')
print('The fixes are completely different: 503 = check CPU/scaling, 502 = check proxy/backend.')
print()

print('=== Now try a SEMANTIC query (no error code) ===')
results2 = ch5.query(query_texts=['upstream server not responding, gateway issue'], n_results=3,
                      include=['documents', 'distances', 'metadatas'])
for i, doc in enumerate(results2['documents'][0]):
    dist = results2['distances'][0][i]
    code = results2['metadatas'][0][i].get('error_code', '-')
    print(f'  {i+1}. (dist: {dist:.4f}) error={code} | {doc[:70]}...')
print()
print('Semantic query finds the right answer. The problem is only with exact codes.')

=== Vector search for "server returns 502" ===
  1. (dist: 0.3546) [WRONG] error=503 | Troubleshooting HTTP 503 Service Unavailable: This error means the ser...
  2. (dist: 0.4113) [CORRECT] error=502 | Troubleshooting HTTP 502 Bad Gateway: This error means the upstream se...
  3. (dist: 0.5689) [WRONG] error=429 | Troubleshooting HTTP 429 Too Many Requests: This error means the clien...
  4. (dist: 0.5697) [WRONG] error=500 | Troubleshooting HTTP 500 Internal Server Error: This error means the s...

The 503 runbook (Service Unavailable) outranks the 502 runbook (Bad Gateway).
The fixes are completely different: 503 = check CPU/scaling, 502 = check proxy/backend.

=== Now try a SEMANTIC query (no error code) ===
  1. (dist: 0.3146) error=502 | Troubleshooting HTTP 502 Bad Gateway: This error means the upstream se...
  2. (dist: 0.6570) error=503 | Troubleshooting HTTP 503 Service Unavailable: This error means the ser...
  3. (dist: 0.6804) error=500 | Troubleshooting HTTP 500 Internal 

### Why does this happen? The Embedding Similarity Proof

The embedding model sees "error 502" and "error 503" as nearly the same concept:
"a server-side HTTP error." The specific number (502 vs 503) carries almost no
semantic weight. But the fixes are completely different.

Let's prove this by embedding the error codes and computing cosine similarity.

In [10]:
# PROOF: Error codes are indistinguishable in vector space
import numpy as np

def cosine_similarity(a, b):
    """Cosine similarity: 1.0 = identical, 0.0 = unrelated."""
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

# Embed the error code strings AS THE USER WOULD TYPE THEM
ef = ch5._embedding_function
error_queries = ['error 401', 'error 403', 'error 500', 'error 502', 'error 503', 'error 504']
fix_queries = [
    'authentication token expired re-login',         # 401 fix
    'user does not have permission access denied',    # 403 fix
]

error_embs = ef(error_queries)
fix_embs = ef(fix_queries)

print('=== Embedding Similarity Between Error Codes ===')
print('(1.0 = identical, 0.0 = unrelated)\n')

# The 5xx codes cluster together
print('Server errors (5xx) - should be DIFFERENT but are nearly identical:')
for i, j in [(2,3), (3,4), (4,5), (2,5)]:
    sim = cosine_similarity(np.array(error_embs[i]), np.array(error_embs[j]))
    print(f'  "{error_queries[i]}" vs "{error_queries[j]}": {sim:.4f}')

print('\nClient errors (4xx):')
sim_401_403 = cosine_similarity(np.array(error_embs[0]), np.array(error_embs[1]))
print(f'  "{error_queries[0]}" vs "{error_queries[1]}": {sim_401_403:.4f}')

print('\nBut the FIXES are different:')
sim_fixes = cosine_similarity(np.array(fix_embs[0]), np.array(fix_embs[1]))
print(f'  401-fix (token expired) vs 403-fix (no permission): {sim_fixes:.4f}')

print('\n--- KEY INSIGHT ---')
sim_502_503 = cosine_similarity(np.array(error_embs[3]), np.array(error_embs[4]))
print(f'  Error 502 vs error 503 similarity: {sim_502_503:.4f}')
print(f'  But 502 fix (check proxy) != 503 fix (check CPU/scaling).')
print(f'  Embeddings see "a server error" but cannot read the specific code.')
print(f'  BM25 keyword search matches "502" exactly and returns only the 502 runbook.')

=== Embedding Similarity Between Error Codes ===
(1.0 = identical, 0.0 = unrelated)

Server errors (5xx) - should be DIFFERENT but are nearly identical:
  "error 500" vs "error 502": 0.6008
  "error 502" vs "error 503": 0.9397
  "error 503" vs "error 504": 0.9389
  "error 500" vs "error 504": 0.6755

Client errors (4xx):
  "error 401" vs "error 403": 0.6004

But the FIXES are different:
  401-fix (token expired) vs 403-fix (no permission): 0.1772

--- KEY INSIGHT ---
  Error 502 vs error 503 similarity: 0.9397
  But 502 fix (check proxy) != 503 fix (check CPU/scaling).
  Embeddings see "a server error" but cannot read the specific code.
  BM25 keyword search matches "502" exactly and returns only the 502 runbook.


In [11]:
# FIX: Route exact-value queries to metadata filter or keyword match
import re

def smart_search(query, collection, n_results=3):
    # Route exact-value queries to filter, semantic queries to vector search.
    # Pattern 1: HTTP error codes (401, 403, 500, 502, etc.)
    error_match = re.search(r'\b(\d{3})\b', query)
    if error_match and any(word in query.lower() for word in ['error', 'http', 'status', 'returns', 'getting']):
        code = error_match.group(1)
        print(f'  Error code detected: {code} -> using metadata filter')
        results = collection.get(
            where={'error_code': code},
            include=['documents', 'metadatas']
        )
        if results['documents']:
            return results

    # Pattern 2: Ticket IDs (TICKET-1234, BUG-5678, etc.)
    ticket_match = re.search(r'TICKET-\d+', query)
    if ticket_match:
        ticket_id = ticket_match.group()
        print(f'  Ticket ID detected: {ticket_id} -> using exact lookup')
        results = collection.get(
            ids=[ticket_id],
            include=['documents', 'metadatas']
        )
        if results['documents']:
            return results

    # Fall back to vector search for semantic queries
    print(f'  No exact value detected -> using vector search')
    return collection.query(
        query_texts=[query], n_results=n_results,
        include=['documents', 'distances', 'metadatas']
    )

# Test 1: Error code query
print('=== FIX: Smart search for "getting error 502" ===')
result = smart_search('getting error 502 on the API', ch5)
doc = result['documents'][0] if isinstance(result['documents'][0], str) else result['documents'][0][0]
print(f'  Found: {doc[:80]}...')

# Test 2: Ticket ID query
print()
print('=== FIX: Smart search for TICKET-1234 ===')
result = smart_search('What is the status of TICKET-1234?', ch5)
doc = result['documents'][0] if isinstance(result['documents'][0], str) else result['documents'][0][0]
print(f'  Found: {doc[:80]}...')

# Test 3: Semantic query (no exact value)
print()
print('=== FIX: Smart search for semantic query ===')
result = smart_search('upstream server not responding', ch5)

=== FIX: Smart search for "getting error 502" ===
  Error code detected: 502 -> using metadata filter
  Found: Troubleshooting HTTP 502 Bad Gateway: This error means the upstream server retur...

=== FIX: Smart search for TICKET-1234 ===
  Ticket ID detected: TICKET-1234 -> using exact lookup
  Found: TICKET-1234: OAuth login times out after 30 seconds on mobile. Steps to reproduc...

=== FIX: Smart search for semantic query ===
  No exact value detected -> using vector search


**Book snippet - Issue 2: When Vector Search Sees the Pattern but Not the Value**

> Vector search for "error 502" returns the 503 runbook first because all server
> errors score 0.94 cosine similarity. The fixes are completely different:
> 502 = check the proxy, 503 = check CPU and auto-scaling.
>
> The fix: hybrid search. BM25 matches the exact string "502".
> Vector search matches meaning. Run both, merge results.


---
## Adding a Second Source: When Everything Changes

So far, all five problems appeared with a single data source: our company wiki.
Temporal drift, vocabulary gaps, and exact-value blindness are all single-source problems.

Now we add a second source: Jira tickets. This introduces two NEW problems
that never appeared with one source alone:
- **ACL Leakage:** Different sources have different access controls. Mix them in one index and data leaks.
- **Multi-Hop:** Answers now span documents from different systems (a ticket + a PR + release notes).


---
## Issue 3: Multi-Source / ACL Leakage

All tenants' data is in one collection. A query from Acme Corp returns
Globex and Wayne data too. This is a data leak.


In [12]:
# PROBLEM: No tenant filtering — cross-tenant data leakage
print('=== Search: "cash reconciliation" (NO tenant filter) ===')
results = ch5.query(
    query_texts=['cash reconciliation discrepancy'], n_results=5,
    include=['documents', 'distances', 'metadatas']
)
tenants_seen = set()
for i, doc in enumerate(results['documents'][0]):
    meta = results['metadatas'][0][i]
    tenant = meta.get('tenant', 'unknown')
    tenants_seen.add(tenant)
    print(f'  {i+1}. [{tenant}] {doc[:70]}...')

print(f'\nDANGER: {len(tenants_seen)} different tenants in results: {tenants_seen}')
print('If user is from Acme Corp, they see Globex and Wayne data.')


=== Search: "cash reconciliation" (NO tenant filter) ===
  1. [acme_corp] Acme Corp: Q4 cash reconciliation shows $2.3M discrepancy in the fixed...
  2. [globex_inc] Globex Inc: Cash balance mismatch of $890K in the equity portfolio. Cu...
  3. [wayne_ent] Wayne Enterprises: Portfolio rebalancing request for Q1. Shift 15% fro...
  4. [acme_corp] Acme Corp: Monthly recon log for November shows all positions matched....
  5. [globex_inc] Globex Inc: Annual compliance review completed. All regulatory filings...

DANGER: 3 different tenants in results: {'acme_corp', 'globex_inc', 'wayne_ent'}
If user is from Acme Corp, they see Globex and Wayne data.


In [13]:
# FIX: Pre-retrieval tenant filter
current_user_tenant = 'acme_corp'  # extracted from JWT token in production

print(f'=== FIX: Search with tenant filter (tenant={current_user_tenant}) ===')
results = ch5.query(
    query_texts=['cash reconciliation discrepancy'], n_results=5,
    where={'tenant': current_user_tenant},  # <-- THIS IS THE FIX
    include=['documents', 'distances', 'metadatas']
)
tenants_seen = set()
for i, doc in enumerate(results['documents'][0]):
    meta = results['metadatas'][0][i]
    tenant = meta.get('tenant', 'unknown')
    tenants_seen.add(tenant)
    print(f'  {i+1}. [{tenant}] {doc[:70]}...')

print(f'\nSAFE: {len(tenants_seen)} tenant(s) in results: {tenants_seen}')


=== FIX: Search with tenant filter (tenant=acme_corp) ===
  1. [acme_corp] Acme Corp: Q4 cash reconciliation shows $2.3M discrepancy in the fixed...
  2. [acme_corp] Acme Corp: Monthly recon log for November shows all positions matched....

SAFE: 1 tenant(s) in results: {'acme_corp'}


In [14]:
# FIX 2: Role-based ACL — block sensitive docs from non-HR users
current_user_role = 'engineer'  # not hr_admin

print(f'=== Search: "salary" as role={current_user_role} (NO ACL filter) ===')
results = ch5.query(
    query_texts=['salary bands engineer'], n_results=3,
    include=['documents', 'metadatas']
)
for i, doc in enumerate(results['documents'][0]):
    meta = results['metadatas'][0][i]
    print(f'  {i+1}. [acl={meta.get("acl_role","none")}] {doc[:70]}...')
print('DANGER: Engineer sees HR salary data!\n')

print(f'=== FIX: Search with ACL filter (role != hr_admin blocked) ===')
results = ch5.query(
    query_texts=['salary bands engineer'], n_results=3,
    where={'acl_role': 'all_employees'},  # only docs accessible to this role
    include=['documents', 'metadatas']
)
for i, doc in enumerate(results['documents'][0]):
    meta = results['metadatas'][0][i]
    print(f'  {i+1}. [acl={meta.get("acl_role","none")}] {doc[:70]}...')
print('SAFE: Only general-access documents returned.')


=== Search: "salary" as role=engineer (NO ACL filter) ===
  1. [acl=hr_admin] HR CONFIDENTIAL: 2024 salary bands. Junior Engineer: $95K-$130K. Senio...
  2. [acl=none] Acme Corp: Monthly recon log for November shows all positions matched....
  3. [acl=none] Globex Inc: Annual compliance review completed. All regulatory filings...
DANGER: Engineer sees HR salary data!

=== FIX: Search with ACL filter (role != hr_admin blocked) ===


  1. [acl=all_employees] PTO Policy: Full-time employees accrue 20 days per year. Contractors d...
SAFE: Only general-access documents returned.


**Book snippet -- Issue 3: ACL Leakage**
> Store `tenant_id` and `acl_role` with every document at ingestion.
> At query time, extract the user's identity from their JWT token and inject
> a `where` filter before the vector search runs. One line of filter, zero data leakage.


---
## Issue 4: Multi-Hop -- Answers Span Documents

"Who fixed the OAuth bug and when was it deployed?" requires information
from a Jira ticket, a pull request, AND the release notes. Single-hop
retrieval only finds the ticket.


In [15]:
# PROBLEM: Single-hop retrieval gets partial answer
print('=== Single-hop: "Who fixed OAuth bug and when deployed?" ===')
results = ch5.query(
    query_texts=['Who fixed the OAuth timeout bug and when was it deployed?'],
    n_results=3, include=['documents', 'distances', 'metadatas']
)
for i, doc in enumerate(results['documents'][0]):
    meta = results['metadatas'][0][i]
    print(f'  {i+1}. [{meta.get("type","?")}] {doc[:80]}...')
    print(f'     Links: ticket={meta.get("linked_ticket","-")} pr={meta.get("linked_pr","-")} '
          f'release={meta.get("linked_release","-")}')

print('\nPROBLEM: May not retrieve all 3 pieces (ticket + PR + release notes).')


=== Single-hop: "Who fixed OAuth bug and when deployed?" ===


  1. [release_notes] Release Notes v2.5.1: Deployed to production on October 15, 2024. Includes fix f...
     Links: ticket=- pr=- release=-
  2. [ticket] TICKET-1234: OAuth login times out after 30 seconds on mobile. Steps to reproduc...
     Links: ticket=- pr=- release=-
  3. [guide] Installation Guide v2.5 (CURRENT): Use the CLI installer. Run: ./install --auto....
     Links: ticket=- pr=- release=-

PROBLEM: May not retrieve all 3 pieces (ticket + PR + release notes).


In [16]:
# FIX: Follow entity links across documents (multi-hop retrieval)
def multi_hop_search(query: str, collection, max_hops=2):
    """Retrieve initial results, then follow metadata links to related docs."""
    # Hop 1: Vector search
    results = collection.query(
        query_texts=[query], n_results=3,
        include=['documents', 'distances', 'metadatas']
    )
    all_docs = {}
    ids_to_fetch = set()

    for i, doc in enumerate(results['documents'][0]):
        meta = results['metadatas'][0][i]
        doc_id = results['ids'][0][i]
        all_docs[doc_id] = {'text': doc, 'meta': meta, 'hop': 0}

        # Collect linked document IDs
        for link_field in ['linked_pr', 'linked_ticket', 'linked_release', 'includes_pr']:
            linked = meta.get(link_field)
            if linked and linked not in all_docs:
                # Map PR-552 -> pr_552, TICKET-9001 -> jira_oauth_bug, etc.
                ids_to_fetch.add(linked)

    # Hop 2+: Fetch linked documents by searching for their references
    for hop in range(max_hops):
        if not ids_to_fetch:
            break
        for ref_id in list(ids_to_fetch):
            # Search for documents mentioning this reference
            ref_results = collection.query(
                query_texts=[ref_id], n_results=1,
                include=['documents', 'metadatas']
            )
            if ref_results['documents'][0]:
                rid = ref_results['ids'][0][0]
                if rid not in all_docs:
                    meta = ref_results['metadatas'][0][0]
                    all_docs[rid] = {
                        'text': ref_results['documents'][0][0],
                        'meta': meta, 'hop': hop + 1
                    }
                    # Follow further links
                    for lf in ['linked_pr', 'linked_ticket', 'linked_release', 'includes_pr']:
                        new_link = meta.get(lf)
                        if new_link and new_link not in all_docs:
                            ids_to_fetch.add(new_link)
            ids_to_fetch.discard(ref_id)

    return all_docs

print('=== FIX: Multi-hop retrieval ===')
docs = multi_hop_search('Who fixed the OAuth timeout bug and when was it deployed?', ch5)
for doc_id, info in docs.items():
    print(f'  [hop {info["hop"]}] [{info["meta"].get("type","?")}] {doc_id}')
    print(f'    {info["text"][:80]}...')
    print()

# Now ask the LLM with ALL the context
full_context = '\n---\n'.join([info['text'] for info in docs.values()])
answer = ask_ai(f"""Using ONLY this context, answer: Who fixed the OAuth timeout bug and when was it deployed?

<context>{full_context}</context>
Answer:""")
print(f'Answer: {answer}')


=== FIX: Multi-hop retrieval ===


  [hop 0] [release_notes] release_v2.5.1
    Release Notes v2.5.1: Deployed to production on October 15, 2024. Includes fix f...

  [hop 0] [ticket] TICKET-1234
    TICKET-1234: OAuth login times out after 30 seconds on mobile. Steps to reproduc...

  [hop 0] [guide] install_guide_v2.5
    Installation Guide v2.5 (CURRENT): Use the CLI installer. Run: ./install --auto....

  [hop 1] [pull_request] pr_552
    PR-552: Fix OAuth token refresh timing. Changed refresh window from 30s to 60s b...

  [hop 2] [ticket] jira_oauth_bug
    TICKET-9001: OAuth timeout bug. Users on mobile cannot login. Root cause: token ...



Answer: The OAuth timeout bug was fixed in **PR-552**. The context does **not explicitly state who authored/fixed it**, but the related ticket was **assigned to Sarah Chen** and PR-552 was **approved by Sarah Chen**.

It was deployed to production in **Release Notes v2.5.1 on October 15, 2024**.


**Book snippet -- Issue 4: Multi-Hop**
> Single-hop retrieval returns the ticket but not the PR or release notes.
> The fix: store entity links (`linked_pr`, `linked_ticket`) as metadata at ingestion,
> then follow those links at query time to collect all related documents before
> sending them to the LLM.


---
## Summary: The Four Fixes

| Issue | Problem | Fix | Where |
|-|-|-|-|
| 1. Temporal drift | Old docs outscore new docs | `where={'superseded': False}` + decay scoring | Both sides |
| 2. Pattern vs value | Error codes, config values indistinguishable | Hybrid search (BM25 + vector) | Query side |
| 3. ACL leakage | Cross-tenant data exposure | `where={'tenant': user_tenant}` from JWT | Query side |
| 4. Multi-hop | Answers span multiple docs | Store entity links, follow at query time | Both sides |

All four fixes share a common pattern: **store richer metadata at ingestion, use it at query time.**


---
## Cleanup

In [17]:
# Optional: delete ch5 collection to start fresh next time
# client.delete_collection('ch5_advanced_rag')
# client.delete_collection('ch5_decay_demo')
# print('Collection deleted')

print(f'Ch5 collection: {ch5.count()} documents')
print(f'Ch4 collection: {book_collection.count()} documents (untouched)')
print('Done.')


Ch5 collection: 26 documents
Ch4 collection: 0 documents (untouched)
Done.
