#!/usr/bin/env python3
"""Generate INDEX.md from per-file frontmatter. Standard library only."""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# directory -> index section heading. Order here is the precedence order.
SECTIONS = [("rules", "Rules"), ("entities", "Entities"),
            ("facts", "Facts"), ("decisions", "Decisions"), ("archive", "Archive (history - not current truth)")]
FM = re.compile(r"\A---\n(.*?)\n---\n", re.S)

def frontmatter(path):
    m = FM.match(open(path, encoding="utf-8").read())
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip()
    return out

def main():
    lines = ["# Knowledge Index", "",
             "<!-- GENERATED by tools/build_index.py - do not hand-edit. -->", ""]
    count = 0
    for d, heading in SECTIONS:
        dirpath = os.path.join(ROOT, d)
        if not os.path.isdir(dirpath):
            continue
        items = []
        for fn in sorted(os.listdir(dirpath)):
            if not fn.endswith(".md"):
                continue
            fm = frontmatter(os.path.join(dirpath, fn))
            name = fm.get("name") or fn[:-3].replace("_", " ")
            hook = fm.get("description", "").rstrip(".")
            items.append(f"- [{name}]({d}/{fn}) - {hook}.")
            count += 1
        if items:
            lines += [f"## {heading}"] + items + [""]
    open(os.path.join(ROOT, "INDEX.md"), "w", encoding="utf-8").write("\n".join(lines))
    print(f"INDEX.md written: {count} items")

if __name__ == "__main__":
    main()
